
* Issue tracker for Hackerman Text

- [[https://github.com/hackerman-inc/text/issues][Issues]]
- [[https://github.com/hackerman-inc/text/discussions/categories/feature-requests][Feature requests]]


** FAQ

*** How to setup code completion

*Ollama*

1. Install Ollama, and download one of the recommended models (e.g. [[https://ollama.com/library/qwen2.5-coder]])
2. Update your ~.hackerman~ config file (/Right-Click/ or ~Cmd + Shift + P~ to open function explorer, then select /Open Config File/)
3. Find and edit this section:

    #+begin_src
    [models]
    
    -- ollama
    code_completion                     ollama, qwen2.5-coder:1.5b
#+end_src

4. Code completion can be triggered with /Code Completion/ (or ~Cmd + K~)

*Mistral*

1. Create Mistral account, and get your api key (see [[https://docs.mistral.ai/getting-started/quickstart]])
2. Update your ~.hackerman~ config file (/Right-Click/ or ~Cmd + Shift + P~ to open function explorer, then select /Open Config File/)
3. Find and edit this section (replace ~API_KEY~ with your Mistral api key):

    #+begin_src
    [models]
    
    -- cloud providers
    code_completion                     mistral, codestral-latest, API_KEY
    #+end_src

4. Code completion can be triggered with /Code Completion/ (or ~Cmd + K~)

*Inception*

1. Create Inception account, and get your api key (see [[https://docs.inceptionlabs.ai/get-started/authentication]])
2. Update your ~.hackerman~ config file (/Right-Click/ or ~Cmd + Shift + P~ to open function explorer, then select /Open Config File/)
3. Find and edit this section (replace ~API_KEY~ with your Inception api key):

    #+begin_src
    [models]
    
    -- cloud providers
    code_completion                     inception, mercury-coder, API_KEY
    #+end_src

4. Code completion can be triggered with /Code Completion/ (or ~Cmd + K~)


*** How to use inline commands

Inline commands can be triggered with /Inline Commands/ (or ~Cmd + Shift + Return~).

*Shell and Python eval*

This feature is only allowed in ~.txt~ and ~.md~ files by default.
You can change allowed files in your ~.hackerman~ config file.

#+begin_src
% echo 'hello'
hello
#+end_src

#+begin_src
42**42
150130937545296572356771972164254457814047970568738777235893533016064
#+end_src

*Org-mode code execution*

You an execute /Python/, /Lua/, /JavaScript/, and /Hy/ code in your ~.org~ files.
Move cursor inside code block and run /Inline Commands/ (or ~Cmd + Shift + Return~).

#+begin_src hylang :var name=Michael
(defn main [name]
    (print "Welcome to Hy in org-mode," name "!")
)
(main name)
#+end_src

#+begin_src
#+RESULTS: True
: Welcome to Hy in org-mode, Michael !
#+end_src

*** How to use custom scripts

This feature is disabled by default.
You can enable in your ~.hackerman~ config file.

#+begin_src
scripts_enabled                     true
allow_unsafe_scripts                false -- allow imports
#+end_src

Scripts are loaded from ~.../Application Support/Hackerman Text/.hackerman-scripts~.
You can provide a path to your own ~.py~ file if stored elsewhere.

#+begin_src
path_to_scripts_file                path/to/plugins.py -- path to scripts file, requires restart
#+end_src

